# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [main]

  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: pages
  cancel-in-progress: true

env:
  FILE: '0_1_intro.py 0_inhalt.py 1_prox_struct.py 2_1_exp_metrik.py 2_2_lpNorm.py 2_4_pexp_fam.py 2_metric_add_segments.py 3_1_add_diff_ps.py 3_2_1_lp_Defbereiche.py 4_quellen.py'  # Source file where scenes are defined
  MANIM: 'manim'  # manim or manimgl - which Manim renderer to use
  SCENES: 'Intro Inhalt Inhalt012 FactorialProximityStructure Inhalt2345 AddSegments LpSegAdditive AddDiffModel pexp_Bsp expMIsoCurves pexpMetrik RecapInhalt567 HinrNotwBeds Inhalt78 lp_Defbereiche Quellen'  # Space-separated list of scenes to render
  USES_TEX: true  # true or false - disabling this will make the action run faster
  DISPLAY: :99  # Do not touch this

jobs:
  # Single deploy job since we're just deploying
  deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: pip

    - name: Install manim dependencies on Ubuntu
      if: ${{ env.MANIM == 'manim' }}
      run: |
        sudo apt-get update
        sudo apt-get install libcairo2-dev libpango1.0-dev ffmpeg freeglut3-dev

    - name: Install manimgl dependencies on Ubuntu
      if: ${{ env.MANIM == 'manimgl' }}
      run: |
        sudo apt-get update
        sudo apt-get install libpango1.0-dev ffmpeg freeglut3-dev xvfb
        nohup Xvfb $DISPLAY &

    - name: Setup TeX Live
      if: ${{ env.USES_TEX == 'true' }}
      uses: teatimeguest/setup-texlive-action@v3
      with:
        packages: >-
          amsmath
          babel-english
          cbfonts-fd
          cm-super
          ctex
          doublestroke
          dvisvgm
          everysel
          fontspec
          frcursive
          fundus-calligra
          gnu-freefont
          jknapltx
          latex-bin
          mathastext
          microtype
          count1to
          multitoc
          prelim2e
          ragged2e
          physics
          preview
          ragged2e
          relsize
          rsfs
          setspace
          standalone
          tipa
          wasy
          wasysym
          xcolor
          xetex
          xkeyval

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Build HTML
      run: |
        ${{ env.MANIM }} 0_1_intro.py Intro
        ${{ env.MANIM }} 0_inhalt.py Inhalt Inhalt012 Inhalt2345 RecapInhalt567 Inhalt78
        ${{ env.MANIM }} 1_prox_struct.py FactorialProximityStructure
        ${{ env.MANIM }} 2_1_exp_metrik.py expMIsoCurves
        ${{ env.MANIM }} 2_2_lpNorm.py LpSegAdditive AddDiffModel
        ${{ env.MANIM }} 2_metric_add_segments.py AddSegments
        ${{ env.MANIM }} 2_4_pexp_fam.py pexpMetrik
        ${{ env.MANIM }} 3_1_add_diff_ps.py HinrNotwBeds
        ${{ env.MANIM }} 3_2_1_lp_Defbereiche.py lp_Defbereiche
        ${{ env.MANIM }} 4_quellen.py Quellen
        manim-slides convert -c progress=true ${{ env.SCENES }} _site/index.html

    - name: Push to gh-pages branch
      if: github.event_name != 'pull_request'
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: _site
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
